-- MySQL Script generated by MySQL Workbench
-- Thu Oct 27 09:42:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portalnotas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portalnotas` ;

-- -----------------------------------------------------
-- Schema portalnotas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portalnotas` DEFAULT CHARACTER SET utf8 ;
USE `portalnotas` ;

-- -----------------------------------------------------
-- Table `portalnotas`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`carrera` (
  `idcarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`idcarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portalnotas`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`estudiante` (
  `carnet` BIGINT NOT NULL,
  `nombres` VARCHAR(100) NULL,
  `apellidos` VARCHAR(100) NULL,
  `fecha_nac` DATE NULL,
  `correo` VARCHAR(100) NULL,
  `telefono` INT NULL,
  `direccion` VARCHAR(250) NULL,
  `dpi` BIGINT NULL,
  `creditos` INT NULL,
  `fecha_creacion` DATE NULL,
  `carrera_idcarrera` INT NOT NULL,
  PRIMARY KEY (`carnet`),
  CONSTRAINT `fk_estudiante_carrera`
    FOREIGN KEY (`carrera_idcarrera`)
    REFERENCES `portalnotas`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_estudiante_carrera_idx` ON `portalnotas`.`estudiante` (`carrera_idcarrera` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portalnotas`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`curso` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `creditos_necesarios` INT NULL,
  `creditos_otorgados` INT NULL,
  `obligatorio` TINYINT NULL,
  `carrera_idcarrera` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_curso_carrera1`
    FOREIGN KEY (`carrera_idcarrera`)
    REFERENCES `portalnotas`.`carrera` (`idcarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_curso_carrera1_idx` ON `portalnotas`.`curso` (`carrera_idcarrera` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portalnotas`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`docente` (
  `siif` INT NOT NULL,
  `nombres` VARCHAR(100) NULL,
  `apellidos` VARCHAR(100) NULL,
  `fecha_nac` DATE NULL,
  `correo` VARCHAR(100) NULL,
  `telefono` INT NULL,
  `direccion` VARCHAR(250) NULL,
  `dpi` BIGINT NULL,
  `fecha_creacion` DATE NULL,
  PRIMARY KEY (`siif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portalnotas`.`cursohabilitado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`cursohabilitado` (
  `idcursohabilitado` INT NOT NULL AUTO_INCREMENT,
  `curso_codigo` INT NOT NULL,
  `ciclo` VARCHAR(2) NULL,
  `docente_siif` INT NOT NULL,
  `cupo` INT NULL,
  `seccion` VARCHAR(1) NULL,
  `anio` YEAR NULL,
  `asignados` INT NULL,
  PRIMARY KEY (`idcursohabilitado`),
  CONSTRAINT `fk_cursohabilitado_curso1`
    FOREIGN KEY (`curso_codigo`)
    REFERENCES `portalnotas`.`curso` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursohabilitado_docente1`
    FOREIGN KEY (`docente_siif`)
    REFERENCES `portalnotas`.`docente` (`siif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cursohabilitado_curso1_idx` ON `portalnotas`.`cursohabilitado` (`curso_codigo` ASC) VISIBLE;

CREATE INDEX `fk_cursohabilitado_docente1_idx` ON `portalnotas`.`cursohabilitado` (`docente_siif` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portalnotas`.`horariocurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`horariocurso` (
  `idhorariocurso` INT NOT NULL AUTO_INCREMENT,
  `cursohabilitado_idcursohabilitado` INT NOT NULL,
  `dia` INT NULL,
  `horario` VARCHAR(100) NULL,
  PRIMARY KEY (`idhorariocurso`),
  CONSTRAINT `fk_horariocurso_cursohabilitado1`
    FOREIGN KEY (`cursohabilitado_idcursohabilitado`)
    REFERENCES `portalnotas`.`cursohabilitado` (`idcursohabilitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_horariocurso_cursohabilitado1_idx` ON `portalnotas`.`horariocurso` (`cursohabilitado_idcursohabilitado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portalnotas`.`asignacioncurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`asignacioncurso` (
  `idasignacioncurso` INT NOT NULL AUTO_INCREMENT,
  `cursohabilitado_idcursohabilitado` INT NOT NULL,
  `estudiante_carnet` BIGINT NOT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`idasignacioncurso`),
  CONSTRAINT `fk_asignacioncurso_cursohabilitado1`
    FOREIGN KEY (`cursohabilitado_idcursohabilitado`)
    REFERENCES `portalnotas`.`cursohabilitado` (`idcursohabilitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacioncurso_estudiante1`
    FOREIGN KEY (`estudiante_carnet`)
    REFERENCES `portalnotas`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portalnotas`.`asignacioncurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`asignacioncurso` (
  `idasignacioncurso` INT NOT NULL AUTO_INCREMENT,
  `cursohabilitado_idcursohabilitado` INT NOT NULL,
  `estudiante_carnet` BIGINT NOT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`idasignacioncurso`),
  CONSTRAINT `fk_asignacioncurso_cursohabilitado1`
    FOREIGN KEY (`cursohabilitado_idcursohabilitado`)
    REFERENCES `portalnotas`.`cursohabilitado` (`idcursohabilitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacioncurso_estudiante1`
    FOREIGN KEY (`estudiante_carnet`)
    REFERENCES `portalnotas`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_asignacioncurso_cursohabilitado1_idx` ON `portalnotas`.`asignacioncurso` (`cursohabilitado_idcursohabilitado` ASC) VISIBLE;

CREATE INDEX `fk_asignacioncurso_estudiante1_idx` ON `portalnotas`.`asignacioncurso` (`estudiante_carnet` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portalnotas`.`desasignacioncurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`desasignacioncurso` (
  `iddesasignacioncurso` INT NOT NULL AUTO_INCREMENT,
  `cursohabilitado_idcursohabilitado` INT NOT NULL,
  `estudiante_carnet` BIGINT NOT NULL,
  PRIMARY KEY (`iddesasignacioncurso`),
  CONSTRAINT `fk_desasignacioncurso_cursohabilitado1`
    FOREIGN KEY (`cursohabilitado_idcursohabilitado`)
    REFERENCES `portalnotas`.`cursohabilitado` (`idcursohabilitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_desasignacioncurso_estudiante1`
    FOREIGN KEY (`estudiante_carnet`)
    REFERENCES `portalnotas`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_desasignacioncurso_cursohabilitado1_idx` ON `portalnotas`.`desasignacioncurso` (`cursohabilitado_idcursohabilitado` ASC) VISIBLE;

CREATE INDEX `fk_desasignacioncurso_estudiante1_idx` ON `portalnotas`.`desasignacioncurso` (`estudiante_carnet` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portalnotas`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`notas` (
  `idnotas` INT NOT NULL AUTO_INCREMENT,
  `cursohabilitado_idcursohabilitado` INT NOT NULL,
  `estudiante_carnet` BIGINT NOT NULL,
  `nota` DECIMAL NULL,
  PRIMARY KEY (`idnotas`),
  CONSTRAINT `fk_notas_cursohabilitado1`
    FOREIGN KEY (`cursohabilitado_idcursohabilitado`)
    REFERENCES `portalnotas`.`cursohabilitado` (`idcursohabilitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_estudiante1`
    FOREIGN KEY (`estudiante_carnet`)
    REFERENCES `portalnotas`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_notas_cursohabilitado1_idx` ON `portalnotas`.`notas` (`cursohabilitado_idcursohabilitado` ASC) VISIBLE;

CREATE INDEX `fk_notas_estudiante1_idx` ON `portalnotas`.`notas` (`estudiante_carnet` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portalnotas`.`actas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portalnotas`.`actas` (
  `idactas` INT NOT NULL AUTO_INCREMENT,
  `cursohabilitado_idcursohabilitado` INT NOT NULL,
  PRIMARY KEY (`idactas`),
  CONSTRAINT `fk_actas_cursohabilitado1`
    FOREIGN KEY (`cursohabilitado_idcursohabilitado`)
    REFERENCES `portalnotas`.`cursohabilitado` (`idcursohabilitado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_actas_cursohabilitado1_idx` ON `portalnotas`.`actas` (`cursohabilitado_idcursohabilitado` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
